### ISSUE TITLE
Site Not Found

### ISSUE THREAD

**Issue by Paarmita** [JessicaML/ScienceMotion-Static#12]
I was going through the project and really found it a cool one to contribute but unfortunately when I tried to visit the live site [](https://jessicaml.github.io/ScienceMotion-Static).
I encountered this error.

![screen shot 2018-02-11 at 8 13 00 pm](https://user-images.githubusercontent.com/26546816/36077184-9acf35e6-0f67-11e8-8742-3e1c19476868.png)

**Comment by JessicaML** [comment]
Thanks Paarmita, back up now :)
