### ISSUE TITLE
Working on Acids and Alkalies

### ISSUE THREAD

**Issue by accakks** [JessicaML/ScienceMotion-Static#23]
Is Acids & Alkalies (https://docs.google.com/spreadsheets/d/1s-CqehOYRcrJmvR3d7WqAs7j7dDJLHuJlcRCXMLvwok/edit#gid=1068197208) open? If so, I'd like to work on that!

**Comment by JessicaML** [comment]
Great Aakanksha! I set the lesson to 'in progress'. It's a long lesson so
you could split it into 2 or 3 parts.

Best wishes,
Jessica

**Comment by accakks** [comment]
@GarimaGill Let's work on this!
