### ISSUE TITLE
Inventions topic quiz

### ISSUE THREAD

**Issue by Paarmita** [JessicaML/ScienceMotion-Static#27]
Is inventions topic still open? @JessicaML 
Saloni and I would like to make a quiz like animations with pic and their names. We could also add this in different categories for physics, chemistry, and biology, divided into various topics.
If this idea looks good to you, Can we work on this?

**Comment by Paarmita** [comment]
@JessicaML Can I start working on this as well?

**Comment by JessicaML** [comment]
Hi Paarmita, I'm really sorry but we would like to have a 'soft launch' after the summer, so we have to concentrate on just adding lesson content instead of quizzes.

**Comment by Paarmita** [comment]
@JessicaML Okay, So I could add some more lessons.

**Comment by JessicaML** [comment]
Thanks Paarmita!
